include: package:effective_dart/analysis_options.1.2.0.yaml

linter: 
  rules:
    public_member_api_docs: false
    avoid_classes_with_only_static_members: false
    
analyzer:
  exclude:
    - example/**